### ISSUE TITLE
Fix role binding issue that does not allow eks view

### ISSUE THREAD

**Issue by opheliah95** [opheliah95/kafka-eks#1]
Your current user or role does not have access to Kubernetes objects on this EKS cluster

This may be due to the current user or role not having Kubernetes RBAC permissions to describe cluster resources or not having an entry in the cluster’s auth config map

**Comment by opheliah95** [comment]
```
mapUsers: |
  - userarn: arn:aws:iam::[account_id]:root
    groups:
    - system:masters
```
A better fix here, see this: https://stackoverflow.com/questions/70787520/your-current-user-or-role-does-not-have-access-to-kubernetes-objects-on-this-eks
